const express = require('express')
const { getAllProducts,createProduct,updateProduct, deleteProduct, getProductDetails, testing } = require('../controllers/productsControllers')
const { isAuthenticatedUser, authorizedRoles } = require('../middlewares/authentication')
const router = express.Router()
router.route("/create-product").post(isAuthenticatedUser,authorizedRoles("admin"),createProduct)
router.route("/products").get(getAllProducts)
router.route("/product/:id").put(isAuthenticatedUser,authorizedRoles("admin"),updateProduct)
router.route("/delete-product/:id").delete(isAuthenticatedUser,authorizedRoles("admin"),deleteProduct)
router.route("/productdetail/:id").get(getProductDetails)
router.route("/testing").get(testing)
module.exports = router